module.exports = {
  testMatch: ['**/__tests__/**/*.test.js'],
  testPathIgnorePatterns: [
    '/node_modules/',
    '/stdd/templates/starters/',
    '/existing-project/',
    '/js-starter-test/',
    '/my-awesome-app/',
    '/py-starter-test/',
    '/ts-starter-test/',
    '/go-starter-test/',
    '/rust-starter-test/',
    '/stdd-integrated-test/',
    '/.claude/',
  ],
  modulePathIgnorePatterns: [
    '<rootDir>/stdd/templates/starters',
  ],
  verbose: true,
  detectOpenHandles: true,
  forceExit: true,
  testTimeout: 15000,
  collectCoverageFrom: [
    'cli.js',
    'src/**/*.js',
    '!src/**/*.test.js',
  ],
  coveragePathIgnorePatterns: [
    '/node_modules/',
    '/stdd/',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov', 'html'],
  coverageThreshold: {
    './src/utils/security.js': {
      branches: 90,
      functions: 100,
      lines: 95,
      statements: 95,
    },
    './src/utils/change-utils.js': {
      branches: 80,
      functions: 85,
      lines: 90,
      statements: 90,
    },
    './src/utils/command-runner.js': {
      branches: 75,
      functions: 80,
      lines: 85,
      statements: 85,
    },
    './src/utils/file-walker.js': {
      branches: 70,
      functions: 85,
      lines: 80,
      statements: 80,
    },
    './src/utils/dynamic-router.js': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    './src/utils/path-resolver.js': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    './src/utils/logger.js': {
      branches: 90,
      functions: 100,
      lines: 95,
      statements: 95,
    },
    './src/utils/workspace-detector.js': {
      branches: 85,
      functions: 100,
      lines: 95,
      statements: 95,
    },
  },
};
