/**
 * Factory Command
 * Test data factory generation using Builder pattern and Faker.js integration.
 */

const fs = require('fs');
const path = require('path');
const chalk = require('chalk');
const { createLogger } = require('../../utils/logger');
const { walkFiles: _walkFiles } = require('../../utils/file-walker');
const _logger = createLogger('factory');

const TYPE_EXTENSIONS = ['.ts', '.tsx', '.js', '.jsx'];
const FACTORY_TEMPLATE = `/**
 * Auto-generated factory for {{typeName}}
 * Generated by STDD Copilot
 */

const { Faker } = require('@faker-js/faker');

class {{typeName}}Factory {
  constructor() {
    this.faker = new Faker('{{locale}}');
    this._overrides = {};
  }

  // Base data generator
  static defaults() {
    return {
{{defaults}}
    };
  }

  // Set override values
  with(values) {
    this._overrides = { ...this._overrides, ...values };
    return this;
  }

  // Build the instance
  build() {
    return {
      ...{{typeName}}Factory.defaults(),
      ...this._overrides,
    };
  }

  // Build multiple instances
  buildMany(count) {
    return Array.from({ length: count }, () => this.build());
  }

  // Preset scenarios
  static valid() {
    return new {{typeName}}Factory().with({
{{validOverrides}}
    });
  }

  static minimal() {
    return new {{typeName}}Factory().with({
{{minimalOverrides}}
    });
  }

  static edgeCase() {
    return new {{typeName}}Factory().with({
{{edgeCaseOverrides}}
    });
  }

  // Field-specific helpers
  withId(id) {
    return this.with({ id });
  }

  withName(name) {
    return this.with({ name });
  }
}

module.exports = { {{typeName}}Factory };
`;

const _INDEX_TEMPLATE = `/**
 * Factory index - exports all factories
 */

{{exports}}
`;

class FactoryCommand {
  constructor(cwd = process.cwd()) {
    this.cwd = cwd;
    this.factoriesDir = path.join(cwd, 'src', '__factories__');
  }

  execute(action = 'generate', args = [], options = {}) {
    switch (action) {
      case 'generate':
      case 'create':
      case 'new':
        return this.generate(args[0], options);
      case 'list':
      case 'ls':
        return this.list(options);
      case 'scan':
        return this.scan(options);
      case 'init':
        return this.init(options);
      case 'scenarios':
        return this.scenarios(options);
      default:
        if (args[0]) return this.generate(action, options);
        return this.list(options);
    }
  }

  init(options = {}) {
    fs.mkdirSync(this.factoriesDir, { recursive: true });

    const pkgPath = path.join(this.cwd, 'package.json');
    if (fs.existsSync(pkgPath)) {
      const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
      if (!pkg.dependencies?.['@faker-js/faker'] && !pkg.devDependencies?.['@faker-js/faker']) {
        if (options.json) {
          console.log(JSON.stringify({ suggestion: 'Install @faker-js/faker: npm install --save-dev @faker-js/faker' }, null, 2));
        } else {
          console.log(chalk.yellow('\n💡 Install @faker-js/faker for realistic test data:\n'));
          console.log('  npm install --save-dev @faker-js/faker\n');
        }
      }
    }

    const indexPath = path.join(this.factoriesDir, 'index.js');
    if (!fs.existsSync(indexPath)) {
      fs.writeFileSync(indexPath, '// Factory exports will be added here\n', 'utf8');
    }

    if (options.json) {
      console.log(JSON.stringify({ initialized: true, path: this.factoriesDir }, null, 2));
    } else {
      console.log(chalk.bold('\n✓ Factory directory initialized\n'));
      console.log(`  ${chalk.cyan(path.relative(this.cwd, this.factoriesDir))}\n`);
    }

    return { initialized: true, path: this.factoriesDir };
  }

  generate(typeName, options = {}) {
    if (!typeName) {
      throw new Error('Type name is required. Usage: stdd factory generate <TypeName>');
    }

    this.init({ ...options, json: true });

    const fields = options.fields ? options.fields.split(',') : [];
    const locale = options.locale || 'en';

    const defaults = this.generateDefaults(typeName, fields);
    const content = FACTORY_TEMPLATE
      .replace(/{{typeName}}/g, typeName)
      .replace(/{{locale}}/g, locale)
      .replace('{{defaults}}', defaults)
      .replace('{{validOverrides}}', defaults)
      .replace('{{minimalOverrides}}', this.generateMinimalOverrides(typeName, fields))
      .replace('{{edgeCaseOverrides}}', this.generateEdgeCaseOverrides(typeName, fields));

    const fileName = `${typeName.toLowerCase()}.factory.js`;
    const filePath = path.join(this.factoriesDir, fileName);

    if (fs.existsSync(filePath) && !options.force) {
      throw new Error(`Factory already exists at ${filePath}. Use --force to overwrite.`);
    }

    fs.writeFileSync(filePath, content, 'utf8');
    this.updateIndex(typeName, fileName);

    if (options.json) {
      console.log(JSON.stringify({ path: filePath, typeName, created: true }, null, 2));
    } else {
      console.log(chalk.bold('\n✓ Factory created\n'));
      console.log(`  ${chalk.cyan(path.relative(this.cwd, filePath))}`);
      console.log(`  Type: ${chalk.cyan(typeName)}`);
      console.log(chalk.dim('\n  Usage:'));
      console.log(`    const { ${typeName}Factory } = require('./__factories__');`);
      console.log(`    const instance = ${typeName}Factory.valid().build();\n`);
    }

    return { path: filePath, typeName, created: true };
  }

  generateDefaults(typeName, fields) {
    const commonFields = {
      id: 'id: this.faker.datatype.uuid(),',
      name: "name: this.faker.person.fullName(),",
      email: 'email: this.faker.internet.email(),',
      title: "title: this.faker.person.jobTitle(),",
      description: 'description: this.faker.lorem.paragraph(),',
      createdAt: "createdAt: this.faker.date.past(),",
      updatedAt: "updatedAt: this.faker.date.recent(),",
      status: "status: this.faker.helpers.arrayElement(['active', 'inactive', 'pending']),",
    };

    if (fields.length === 0) {
      fields = ['id', 'name', 'createdAt'];
    }

    return fields.map(f => commonFields[f] || `  ${f}: this.faker.lorem.word(),`).join('\n');
  }

  generateMinimalOverrides(typeName, fields) {
    return fields.slice(0, 2).map(f => {
      const value = f === 'id' ? "'min-id'" : "'minimal value'";
      return `      ${f}: ${value},`;
    }).join('\n');
  }

  generateEdgeCaseOverrides(typeName, fields) {
    return fields.slice(0, 3).map(f => {
      if (f === 'id') return `      ${f}: '';`;
      if (f === 'name') return `      ${f}: 'A'.repeat(500);`;
      return `      ${f}: null;`;
    }).join('\n');
  }

  updateIndex(typeName, fileName) {
    const indexPath = path.join(this.factoriesDir, 'index.js');
    let content = '';
    if (fs.existsSync(indexPath)) {
      content = fs.readFileSync(indexPath, 'utf8');
    }

    const exportLine = `const { ${typeName}Factory } = require('./${fileName.replace('.js', '')}');`;
    const requireLine = `  ${typeName}Factory,`;

    if (!content.includes(exportLine)) {
      content = content.replace('// Factory exports will be added here', '');
      const lines = content.split('\n').filter(Boolean);

      const requires = lines.filter(l => l.startsWith('const'));
      const exports = lines.filter(l => l.startsWith('module.exports'));

      const newContent = [
        ...requires,
        exportLine,
        '',
        'module.exports = {',
        ...exports.map(l => l.replace('}', '').replace('module.exports = {', '').trim()).filter(Boolean),
        requireLine,
        '};',
      ].join('\n');

      fs.writeFileSync(indexPath, newContent + '\n', 'utf8');
    }
  }

  list(options = {}) {
    if (!fs.existsSync(this.factoriesDir)) {
      if (options.json) {
        console.log(JSON.stringify({ factories: [] }, null, 2));
      } else {
        console.log(chalk.yellow('\nNo factories found. Run "stdd factory generate <TypeName>" to create one.\n'));
      }
      return { factories: [] };
    }

    const factories = fs.readdirSync(this.factoriesDir)
      .filter(f => f.endsWith('.factory.js'))
      .map(f => {
        const typeName = f.replace('.factory.js', '').replace(/(^|\\s)\\S/g, t => t.toUpperCase());
        const stat = fs.statSync(path.join(this.factoriesDir, f));
        return {
          file: f,
          typeName: typeName.charAt(0).toUpperCase() + typeName.slice(1),
          size: stat.size,
          modified: stat.mtime,
        };
      });

    if (options.json) {
      console.log(JSON.stringify({ factories, count: factories.length }, null, 2));
    } else {
      console.log(chalk.bold('\nTest Data Factories\n'));
      if (factories.length === 0) {
        console.log('  No factories found.\n');
      } else {
        factories.forEach((factory, i) => {
          console.log(`  ${chalk.cyan((i + 1).toString() + '.')} ${chalk.bold(factory.typeName)}`);
          console.log(`      ${chalk.dim(factory.file)} · ${chalk.dim(factory.modified.toLocaleDateString())}\n`);
        });
      }
    }

    return { factories, count: factories.length };
  }

  scan(options = {}) {
    const typePaths = ['src', 'lib', 'app']
      .map(p => path.join(this.cwd, p))
      .filter(p => fs.existsSync(p));

    const types = new Set();
    for (const root of typePaths) {
      const files = _walkFiles(root, { extensions: TYPE_EXTENSIONS });
      for (const file of files) {
        const content = fs.readFileSync(file, 'utf8');
        const matches = content.match(/(?:class|interface|type)\s+(\w+)/g) || [];
        matches.forEach(m => {
          const typeName = m.split(/\s+/)[1];
          if (typeName && typeName.length > 2 && /^[A-Z]/.test(typeName)) {
            types.add(typeName);
          }
        });
      }
    }

    const typeList = Array.from(types).sort();

    if (options.json) {
      console.log(JSON.stringify({ types: typeList, count: typeList.length }, null, 2));
    } else {
      console.log(chalk.bold('\nDiscovered Types\n'));
      console.log(`  Found ${chalk.cyan(typeList.length.toString())} potential factory types:\n`);
      typeList.forEach(type => {
        console.log(`  • ${chalk.cyan(type)}`);
      });
      console.log(chalk.dim('\n  Generate factories with: stdd factory generate <TypeName>\n'));
    }

    return { types: typeList, count: typeList.length };
  }

  scenarios(options = {}) {
    const scenariosPath = path.join(this.factoriesDir, 'scenarios.js');

    const scenariosTemplate = `/**
 * Predefined test scenarios using factories
 * Generated by STDD Copilot
 */

const factories = require('./index');

/**
 * Scenario: Valid entity creation
 */
function validEntity(factoryName) {
  const Factory = factories[factoryName + 'Factory'];
  return Factory ? Factory.valid().build() : null;
}

/**
 * Scenario: Minimal entity (required fields only)
 */
function minimalEntity(factoryName) {
  const Factory = factories[factoryName + 'Factory'];
  return Factory ? Factory.minimal().build() : null;
}

/**
 * Scenario: Edge case entity (boundary values)
 */
function edgeCaseEntity(factoryName) {
  const Factory = factories[factoryName + 'Factory'];
  return Factory ? Factory.edgeCase().build() : null;
}

/**
 * Scenario: Collection of entities
 */
function entityCollection(factoryName, count = 10) {
  const Factory = factories[factoryName + 'Factory'];
  return Factory ? Factory.valid().buildMany(count) : [];
}

module.exports = {
  validEntity,
  minimalEntity,
  edgeCaseEntity,
  entityCollection,
};
`;

    fs.mkdirSync(this.factoriesDir, { recursive: true });
    fs.writeFileSync(scenariosPath, scenariosTemplate, 'utf8');

    if (options.json) {
      console.log(JSON.stringify({ path: scenariosPath, created: true }, null, 2));
    } else {
      console.log(chalk.bold('\n✓ Scenarios file created\n'));
      console.log(`  ${chalk.cyan(path.relative(this.cwd, scenariosPath))}`);
      console.log(chalk.dim('\n  Usage:'));
      console.log(`    const { validEntity, entityCollection } = require('./__factories__/scenarios');`);
      console.log(`    const user = validEntity('User');\n`);
    }

    return { path: scenariosPath, created: true };
  }
}

module.exports = { FactoryCommand };
