/**
 * STDD CLI Commands Index
 */

module.exports = {
  InitCommand: require('./init').InitCommand,
  UpdateCommand: require('./update').UpdateCommand,
  ListCommand: require('./list').ListCommand,
  NewCommand: require('./new').NewCommand,
  StatusCommand: require('./status').StatusCommand,
  ApplyCommand: require('./apply').ApplyCommand,
  VerifyCommand: require('./verify').VerifyCommand,
  ArchiveCommand: require('./archive').ArchiveCommand,
  FFCommand: require('./ff').FFCommand,
  TurboCommand: require('./turbo').TurboCommand,
  MetricsCommand: require('./metrics').MetricsCommand,
  GuardCommand: require('./guard').GuardCommand,
  MutationCommand: require('./mutation').MutationCommand,
  ExploreCommand: require('./explore').ExploreCommand,
  StartersCommand: require('./starters').StartersCommand,
  ContinueCommand: require('./continue').ContinueCommand,
  IssueCommand: require('./issue').IssueCommand,
  CommitCommand: require('./commit-msg').CommitCommand,
  ContextCommand: require('./context').ContextCommand,
  CiGeneratorCommand: require('./ci-generator').CiGeneratorCommand,
  RecommendEngine: require('./recommend').RecommendEngine,
  printRecommendations: require('./recommend').printRecommendations,
  ApiSpecCommand: require('./api-spec').ApiSpecCommand,
  GraphRunCommand: require('./graph-run').GraphRunCommand,
  ConstitutionFixCommand: require('./constitution-fix').ConstitutionFixCommand,
  AuditCommand: require('./audit').AuditCommand,
  WorkspaceCommand: require('./workspace').WorkspaceCommand,
  DepcheckCommand: require('./depcheck').DepcheckCommand,
  SchemaCommand: require('./schema').SchemaCommand,
  ContractCommand: require('./contract').ContractCommand,
  MockGenCommand: require('./mock-gen').MockGenCommand,
  ValidateCommand: require('./validate').ValidateCommand,
  LearnCommand: require('./learn').LearnCommand,
  RolesCommand: require('./roles').RolesCommand,
  ExtensionsCommand: require('./extensions').ExtensionsCommand,
  StoryCommand: require('./story').StoryCommand,
  UserTestCommand: require('./user-test').UserTestCommand,
  PipelineCommand: require('./pipeline').PipelineCommand,
  FixPacketCommand: require('./fix-packet').FixPacketCommand,
  OutsideInCommand: require('./outside-in').OutsideInCommand,
  AgentEngine: require('../../runtime/agent-simulator').AgentEngine,
  SudoLangParser: require('../../runtime/sudolang-parser').SudoLangParser,
  BabyStepsCommand: require('./baby-steps').BabyStepsCommand,
  ElicitationCommand: require('./elicitation').ElicitationCommand,
  SudoExecutor: require('../../runtime/sudolang-executor').SudoExecutor,
  BrowserDoctor: require('../../runtime/browser-doctor').BrowserDoctor,
  createAgentExecutor: require('../../runtime/agents').createAgentExecutor,
  StartCommand: require('./start').StartCommand,
  DoctorCommand: require('./doctor').DoctorCommand,
};
