/**
 * STDD CLI Commands Index
 *
 * Only symbols imported via destructuring in cli.js are exported here.
 * Symbols imported directly from their source modules (e.g. graphCommand from
 * ./graph, MemoryScanner from ./memory-scan) are NOT re-exported to avoid
 * redundant aliasing and circular-reference risk.
 */

module.exports = {
  InitCommand: require('./init').InitCommand,
  UpdateCommand: require('./update').UpdateCommand,
  ListCommand: require('./list').ListCommand,
  NewCommand: require('./new').NewCommand,
  StatusCommand: require('./status').StatusCommand,
  ApplyCommand: require('./apply').ApplyCommand,
  VerifyCommand: require('./verify').VerifyCommand,
  ArchiveCommand: require('./archive').ArchiveCommand,
  FFCommand: require('./ff').FFCommand,
  TurboCommand: require('./turbo').TurboCommand,
  MetricsCommand: require('./metrics').MetricsCommand,
  GuardCommand: require('./guard').GuardCommand,
  MutationCommand: require('./mutation').MutationCommand,
  ExploreCommand: require('./explore').ExploreCommand,
  StartersCommand: require('./starters').StartersCommand,
  ContinueCommand: require('./continue').ContinueCommand,
  IssueCommand: require('./issue').IssueCommand,
  CommitCommand: require('./commit-msg').CommitCommand,
  ContextCommand: require('./context').ContextCommand,
  CiGeneratorCommand: require('./ci-generator').CiGeneratorCommand,
  RecommendEngine: require('./recommend').RecommendEngine,
  printRecommendations: require('./recommend').printRecommendations,
  ApiSpecCommand: require('./api-spec').ApiSpecCommand,
  ConstitutionFixCommand: require('./constitution-fix').ConstitutionFixCommand,
  AuditCommand: require('./audit').AuditCommand,
  WorkspaceCommand: require('./workspace').WorkspaceCommand,
  DepcheckCommand: require('./depcheck').DepcheckCommand,
  SchemaCommand: require('./schema').SchemaCommand,
  ContractCommand: require('./contract').ContractCommand,
  MockGenCommand: require('./mock-gen').MockGenCommand,
  ValidateCommand: require('./validate').ValidateCommand,
  LearnCommand: require('./learn').LearnCommand,
  RolesCommand: require('./roles').RolesCommand,
  ExtensionsCommand: require('./extensions').ExtensionsCommand,
  StoryCommand: require('./story').StoryCommand,
  UserTestCommand: require('./user-test').UserTestCommand,
  PipelineCommand: require('./pipeline').PipelineCommand,
  FixPacketCommand: require('./fix-packet').FixPacketCommand,
  OutsideInCommand: require('./outside-in').OutsideInCommand,
  AgentEngine: require('../../runtime/agent-simulator').AgentEngine,
  SudoLangParser: require('../../runtime/sudolang-parser').SudoLangParser,
  BabyStepsCommand: require('./baby-steps').BabyStepsCommand,
  ElicitationCommand: require('./elicitation').ElicitationCommand,
  SudoExecutor: require('../../runtime/sudolang-executor').SudoExecutor,
  createAgentExecutor: require('../../runtime/agents').createAgentExecutor,
  StartCommand: require('./start').StartCommand,
  DoctorCommand: require('./doctor').DoctorCommand,
  SkillsCommand: require('./skills').SkillsCommand,
  CommandsCommand: require('./commands').CommandsCommand,
  GraphHistoryCommand: require('./graph-history').GraphHistoryCommand,
  GraphRunCommand: require('./graph-run').GraphRunCommand,
  WaiverManagerCommand: require('./waiver-manager-command').WaiverManagerCommand,
  ProductProposalCommand: require('./product-proposal').ProductProposalCommand,
  // New CLI commands for previously Skill-only features
  VisionCommand: require('./vision').VisionCommand,
  PrpCommand: require('./prp').PrpCommand,
  DesignCommand: require('./design').DesignCommand,
  CertaintyCommand: require('./certainty').CertaintyCommand,
  ComplexityCommand: require('./complexity').ComplexityCommand,
  FactoryCommand: require('./factory').FactoryCommand,
  MockCommand: require('./mock').MockCommand,
  MemoryCommand: require('./memory').MemoryCommand,
  IterateCommand: require('./iterate').IterateCommand,
  HelpCommand: require('./help').HelpCommand,
  ParallelCommand: require('./parallel').ParallelCommand,
  SupervisorCommand: require('./supervisor').SupervisorCommand,
  // Skill-based workflow commands
  ProposeCommand: require('./propose').ProposeCommand,
  ClarifyCommand: require('./clarify').ClarifyCommand,
  ConfirmCommand: require('./confirm').ConfirmCommand,
  PlanCommand: require('./plan').PlanCommand,
  ExecuteCommand: require('./execute').ExecuteCommand,
  FinalDocCommand: require('./final-doc').FinalDocCommand,
  CommitTddCommand: require('./commit-tdd').CommitTddCommand,
  ProfileCommand: require('./profile').ProfileCommand,
  UICommand: require('./ui').UICommand,
  BuilderCommand: require('./builder').BuilderCommand,
  ModulesCommand: require('./modules').ModulesCommand,
  DocsCommand: require('./docs').DocsCommand,
  DashboardCommand: require('./dashboard').DashboardCommand,
  AdaptCommand: require('./adapt').AdaptCommand,
  McpCommand: require('./mcp').McpCommand,
  AgentCommand: require('./agent').AgentCommand,
};
