/**
 * Memory Scan Command
 * Scans project source code and generates components.md and contracts.md
 */

const fs = require('fs').promises;
const path = require('path');
const yaml = require('js-yaml');
const chalk = require('chalk');

class MemoryScanner {
  constructor(cwd = process.cwd()) {
    this.cwd = cwd;
    this.sourceRoot = null;
    this.extensions = ['.js', '.ts', '.jsx', '.tsx', '.py'];
  }

  async resolveConfig() {
    const configPath = path.join(this.cwd, 'stdd', 'config.yaml');
    let config = {};
    try {
      const content = await fs.readFile(configPath, 'utf-8');
      config = yaml.load(content) || {};
    } catch {
      // No config, use defaults
    }
    this.sourceRoot = config.source_root
      ? path.resolve(this.cwd, config.source_root)
      : path.join(this.cwd, 'src');
  }

  async scan(options = {}) {
    await this.resolveConfig();

    const sourceDir = options.sourceDir || this.sourceRoot;
    const memoryDir = path.join(this.cwd, 'stdd', 'memory');

    // Ensure memory dir exists
    await fs.mkdir(memoryDir, { recursive: true });

    const files = await this.findSourceFiles(sourceDir);
    const componentsMd = this.generateComponentsMd(files);
    const contractsMd = await this.generateContractsMd(files);

    const componentsPath = path.join(memoryDir, 'components.md');
    const contractsPath = path.join(memoryDir, 'contracts.md');

    await fs.writeFile(componentsPath, componentsMd, 'utf-8');
    await fs.writeFile(contractsPath, contractsMd, 'utf-8');

    return {
      componentsPath,
      contractsPath,
      fileCount: files.length
    };
  }

  async findSourceFiles(dir) {
    const results = [];
    try {
      const entries = await fs.readdir(dir, { withFileTypes: true });
      for (const entry of entries) {
        const fullPath = path.join(dir, entry.name);
        if (entry.isDirectory() && !entry.name.startsWith('.') && entry.name !== 'node_modules') {
          const subFiles = await this.findSourceFiles(fullPath);
          results.push(...subFiles);
        } else if (entry.isFile()) {
          const ext = path.extname(entry.name).toLowerCase();
          if (this.extensions.includes(ext)) {
            results.push(fullPath);
          }
        }
      }
    } catch {
      // Skip unreadable directories
    }
    return results;
  }

  generateComponentsMd(files) {
    const timestamp = new Date().toISOString();
    const tree = this.buildFileTree(files);

    let md = `# Components Memory - 组件架构

> Auto-generated by \`stdd memory scan\` at ${timestamp}

## 源码目录结构

\`\`\`
${tree}
\`\`\`

## 组件清单

`;

    // Group files by directory
    const groups = {};
    for (const file of files) {
      const relPath = path.relative(this.cwd, file);
      const dir = path.dirname(relPath);
      if (!groups[dir]) {
        groups[dir] = [];
      }
      groups[dir].push(path.basename(file));
    }

    for (const [dir, filenames] of Object.entries(groups)) {
      md += `### ${dir}/\n\n`;
      for (const filename of filenames) {
        const purpose = this.inferPurpose(filename, dir);
        md += `- [${filename}](${path.join(dir, filename)}) - ${purpose}\n`;
      }
      md += '\n';
    }

    return md;
  }

  buildFileTree(files) {
    if (files.length === 0) return '(no source files found)';

    const tree = {};
    for (const file of files) {
      const relPath = path.relative(this.cwd, file);
      const parts = relPath.split(path.sep);
      this.addToTree(tree, parts);
    }

    return this.renderTree(tree, '');
  }

  addToTree(tree, parts) {
    let current = tree;
    for (const part of parts) {
      if (!current[part]) {
        current[part] = {};
      }
      current = current[part];
    }
  }

  renderTree(tree, prefix, _isLast = false) {
    const lines = [];
    const entries = Object.keys(tree).sort();

    entries.forEach((name, index) => {
      const isLastEntry = index === entries.length - 1;
      const connector = isLastEntry ? '└── ' : '├── ';
      const isDir = Object.keys(tree[name]).length > 0;

      lines.push(`${prefix}${connector}${name}${isDir ? '/' : ''}`);

      if (isDir) {
        const newPrefix = prefix + (isLastEntry ? '    ' : '│   ');
        lines.push(this.renderTree(tree[name], newPrefix, isLastEntry));
      }
    });

    return lines.filter(l => l !== undefined).join('\n');
  }

  inferPurpose(filename, dir) {
    const name = path.basename(filename, path.extname(filename));
    const lowerDir = dir.toLowerCase();
    const lowerName = name.toLowerCase();

    // Common patterns
    if (lowerDir.includes('component') || lowerDir.includes('components')) {
      if (lowerName.includes('button')) return 'Button UI component';
      if (lowerName.includes('input')) return 'Input field component';
      if (lowerName.includes('modal')) return 'Modal dialog component';
      if (lowerName.includes('header')) return 'Header component';
      if (lowerName.includes('footer')) return 'Footer component';
      if (lowerName.includes('form')) return 'Form component';
      if (lowerName.includes('list')) return 'List display component';
      if (lowerName.includes('table')) return 'Table display component';
      if (lowerName.includes('card')) return 'Card component';
      if (lowerName.includes('nav')) return 'Navigation component';
      return 'UI Component';
    }
    if (lowerDir.includes('util') || lowerDir.includes('helper')) {
      if (lowerName.includes('validate')) return 'Validation helpers';
      if (lowerName.includes('format')) return 'Formatting utilities';
      if (lowerName.includes('string')) return 'String utilities';
      if (lowerName.includes('array')) return 'Array utilities';
      if (lowerName.includes('math')) return 'Math utilities';
      if (lowerName.includes('date')) return 'Date utilities';
      return 'Utility functions';
    }
    if (lowerDir.includes('service')) {
      if (lowerName.includes('auth')) return 'Authentication service';
      if (lowerName.includes('api')) return 'API client service';
      if (lowerName.includes('user')) return 'User service';
      if (lowerName.includes('data')) return 'Data service';
      return 'Business logic service';
    }
    if (lowerDir.includes('model') || lowerDir.includes('entity')) {
      return 'Data model definition';
    }
    if (lowerDir.includes('controller')) {
      return 'Request handler controller';
    }
    if (lowerDir.includes('route') || lowerDir.includes('router')) {
      return 'Route definitions';
    }
    if (lowerDir.includes('config') || lowerDir.includes('conf')) {
      return 'Configuration module';
    }
    if (lowerDir.includes('test') || lowerDir.includes('spec')) {
      return 'Test suite';
    }
    if (lowerDir.includes('middleware')) {
      return 'Request middleware';
    }
    if (lowerDir.includes('hook')) {
      return 'Custom hook';
    }

    // Name-based inference
    if (lowerName.includes('index')) return 'Module entry point';
    if (lowerName.includes('app')) return 'Application entry';
    if (lowerName.includes('main')) return 'Main entry point';
    if (lowerName.includes('config')) return 'Configuration';
    if (lowerName.includes('constant')) return 'Constants definition';
    if (lowerName.includes('type')) return 'Type definitions';
    if (lowerName.includes('interface')) return 'Interface definitions';

    return 'Source module';
  }

  async generateContractsMd(files) {
    const timestamp = new Date().toISOString();

    let md = `# 接口契约与类型定义簿 (Contracts)

> Auto-generated by \`stdd memory scan\` at ${timestamp}

## API Surface

`;

    const contracts = [];
    for (const file of files) {
      const relPath = path.relative(this.cwd, file);
      const ext = path.extname(file).toLowerCase();

      let symbols = [];
      if (['.js', '.ts', '.jsx', '.tsx'].includes(ext)) {
        symbols = await this.extractJSSymbols(file);
      } else if (ext === '.py') {
        symbols = await this.extractPySymbols(file);
      }

      if (symbols.length > 0) {
        contracts.push({ relPath, symbols });
      }
    }

    if (contracts.length === 0) {
      md += '*No exported symbols found.*\n';
      return md;
    }

    for (const { relPath, symbols } of contracts) {
      md += `### \`${relPath}\`\n\n`;
      md += '| Export | Type | Signature |\n';
      md += '|--------|------|----------|\n';

      for (const sym of symbols) {
        md += `| \`${sym.name}\` | ${sym.type} | \`${sym.signature || ''}\` |\n`;
      }
      md += '\n';
    }

    return md;
  }

  async extractJSSymbols(filePath) {
    const symbols = [];
    try {
      const content = await fs.readFile(filePath, 'utf-8');
      const lines = content.split('\n');

      // First: extract module.exports = { ... } (may span multiple lines)
      const moduleExportMatch = content.match(/module\.exports\s*=\s*\{([\s\S]*?)\}/m);
      if (moduleExportMatch) {
        const names = moduleExportMatch[1]
          .split(',')
          .map(n => n.trim().replace(/\n/g, '').split(/\s*:\s*/)[0])
          .filter(Boolean);
        for (const name of names) {
          symbols.push({ name, type: 'exports', signature: '' });
        }
      }

      for (const line of lines) {
        const trimmed = line.trim();

        // export function name(
        let match = trimmed.match(/export\s+(async\s+)?function\s+(\w+)\s*\(([^)]*)\)/);
        if (match) {
          symbols.push({
            name: match[2],
            type: 'function',
            signature: `${match[1] || ''}function(${match[3]})`
          });
          continue;
        }

        // export const name = (
        // export const name = async (
        match = trimmed.match(/export\s+const\s+(\w+)\s*=\s*(async\s+)?\(?/);
        if (match) {
          symbols.push({
            name: match[1],
            type: 'const',
            signature: match[2] ? 'async arrow' : 'arrow/function'
          });
          continue;
        }

        // export class name
        match = trimmed.match(/export\s+(abstract\s+)?class\s+(\w+)(\s+extends\s+\w+)?/);
        if (match) {
          symbols.push({
            name: match[2],
            type: 'class',
            signature: match[3] ? match[3].trim() : ''
          });
          continue;
        }

        // export interface name (TypeScript)
        match = trimmed.match(/export\s+interface\s+(\w+)/);
        if (match) {
          symbols.push({
            name: match[1],
            type: 'interface',
            signature: ''
          });
          continue;
        }

        // export type name = (TypeScript)
        match = trimmed.match(/export\s+type\s+(\w+)\s*=/);
        if (match) {
          symbols.push({
            name: match[1],
            type: 'type',
            signature: ''
          });
          continue;
        }

        // exports.name = function
        match = trimmed.match(/exports\.(\w+)\s*=/);
        if (match) {
          symbols.push({
            name: match[1],
            type: 'exports',
            signature: ''
          });
        }
      }
    } catch {
      // Skip unreadable files
    }
    return symbols;
  }

  async extractPySymbols(filePath) {
    const symbols = [];
    try {
      const content = await fs.readFile(filePath, 'utf-8');
      const lines = content.split('\n');

      for (const line of lines) {
        // def name(
        let match = line.match(/^def\s+(\w+)\s*\(([^)]*)\)/);
        if (match) {
          symbols.push({
            name: match[1],
            type: 'function',
            signature: `def(${match[2]})`
          });
          continue;
        }

        // class name(
        match = line.match(/^class\s+(\w+)(\s*\([^)]*\))?/);
        if (match) {
          symbols.push({
            name: match[1],
            type: 'class',
            signature: match[2] ? match[2].trim() : ''
          });
        }
      }
    } catch {
      // Skip unreadable files
    }
    return symbols;
  }

  async listMemory() {
    const memoryDir = path.join(this.cwd, 'stdd', 'memory');
    try {
      const entries = await fs.readdir(memoryDir);
      const files = [];

      for (const entry of entries) {
        const fullPath = path.join(memoryDir, entry);
        const stat = await fs.stat(fullPath);
        if (stat.isFile()) {
          files.push({
            name: entry,
            path: fullPath,
            size: stat.size,
            modified: stat.mtime
          });
        }
      }

      return files.sort((a, b) => b.modified - a.modified);
    } catch (error) {
      if (error.code === 'ENOENT') {
        console.log(chalk.yellow('Memory directory not found. Run `stdd init` first.'));
        return [];
      }
      throw error;
    }
  }
}

module.exports = { MemoryScanner };
