/**
 * Mock Command
 * Mock generation (alias to mock-gen with additional functionality).
 */

const fs = require('fs');
const path = require('path');
const chalk = require('chalk');
const { createLogger } = require('../../utils/logger');
const { MockGenCommand } = require('./mock-gen');
const _logger = createLogger('mock');

class MockCommand extends MockGenCommand {
  constructor(cwd = process.cwd()) {
    super(cwd);
    this.mocksDir = path.join(cwd, 'src', '__mocks__');
  }

  execute(action = 'generate', args = [], options = {}) {
    switch (action) {
      case 'generate':
      case 'create':
      case 'new':
        return this.generate(args[0], options);
      case 'list':
      case 'ls':
        return this.list(options);
      case 'scan':
        return this.scan(options);
      case 'init':
        return this.init(options);
      case 'module':
        return this.generateModuleMock(args[0], options);
      case 'function':
        return this.generateFunctionMock(args[0], options);
      case 'api':
        return this.generateApiMock(args[0], options);
      default:
        if (args[0]) return this.generate(action, options);
        return this.list(options);
    }
  }

  init(options = {}) {
    fs.mkdirSync(this.mocksDir, { recursive: true });

    const gitignorePath = path.join(this.cwd, '.gitignore');
    let gitignore = '';
    if (fs.existsSync(gitignorePath)) {
      gitignore = fs.readFileSync(gitignorePath, 'utf8');
    }
    if (!gitignore.includes('__mocks__')) {
      fs.appendFileSync(gitignorePath, '\n# Test mocks\nsrc/__mocks__/\n', 'utf8');
    }

    if (options.json) {
      console.log(JSON.stringify({ initialized: true, path: this.mocksDir }, null, 2));
    } else {
      console.log(chalk.bold('\n✓ Mock directory initialized\n'));
      console.log(`  ${chalk.cyan(path.relative(this.cwd, this.mocksDir))}\n`);
    }

    return { initialized: true, path: this.mocksDir };
  }

  generate(target, options = {}) {
    this.init({ ...options, json: true });

    if (!target) {
      throw new Error('Target is required. Usage: stdd mock generate <module|function|api>');
    }

    const mockPath = path.join(this.mocksDir, `${target}.js`);
    const content = this.generateMockContent(target, options);

    if (fs.existsSync(mockPath) && !options.force) {
      throw new Error(`Mock already exists at ${mockPath}. Use --force to overwrite.`);
    }

    fs.writeFileSync(mockPath, content, 'utf8');

    if (options.json) {
      console.log(JSON.stringify({ path: mockPath, target, created: true }, null, 2));
    } else {
      console.log(chalk.bold('\n✓ Mock created\n'));
      console.log(`  ${chalk.cyan(path.relative(this.cwd, mockPath))}`);
      console.log(`  Target: ${chalk.cyan(target)}\n`);
    }

    return { path: mockPath, target, created: true };
  }

  generateMockContent(target, options = {}) {
    const type = options.type || this.detectType(target);

    switch (type) {
      case 'api':
        return this.generateApiMockContent(target, options);
      case 'function':
        return this.generateFunctionMockContent(target, options);
      case 'module':
      default:
        return this.generateModuleMockContent(target, options);
    }
  }

  detectType(target) {
    if (target.includes('/api/') || target.includes('-api') || target.endsWith('Api')) return 'api';
    if (target.startsWith('use') || target.startsWith('get') || target.startsWith('fetch')) return 'function';
    return 'module';
  }

  generateModuleMockContent(target, _options = {}) {
    return `/**
 * Mock for ${target}
 * Generated by STDD Copilot
 */

const originalModule = jest.requireActual('${target}');

module.exports = {
  ...originalModule,
  // Override specific exports here
  exampleFunction: jest.fn(() => ({
    id: 'mock-id',
    name: 'Mock Name',
  })),
};
`;
  }

  generateFunctionMockContent(functionName, _options = {}) {
    return `/**
 * Mock function for ${functionName}
 * Generated by STDD Copilot
 */

function ${functionName}() {
  return {
    id: 'mock-id',
    data: {},
    status: 'success',
  };
}

module.exports = { ${functionName} };
`;
  }

  generateApiMockContent(apiName, options = {}) {
    const methods = options.methods || ['get', 'post', 'put', 'delete'];

    return `/**
 * API mock for ${apiName}
 * Generated by STDD Copilot
 */

const mockHandlers = {
${methods.map(m => `  ${m.toUpperCase()}: jest.fn((req, res) => {
    res.status(200).json({ success: true, data: {} });
  }),`).join('\n')}
};

module.exports = mockHandlers;
module.exports.default = mockHandlers;
`;
  }

  generateModuleMock(modulePath, options = {}) {
    return this.generate(modulePath, { ...options, type: 'module' });
  }

  generateFunctionMock(functionName, options = {}) {
    return this.generate(functionName, { ...options, type: 'function' });
  }

  generateApiMock(apiPath, options = {}) {
    return this.generate(apiPath, { ...options, type: 'api' });
  }

  list(options = {}) {
    if (!fs.existsSync(this.mocksDir)) {
      if (options.json) {
        console.log(JSON.stringify({ mocks: [] }, null, 2));
      } else {
        console.log(chalk.yellow('\nNo mocks found. Run "stdd mock generate <target>" to create one.\n'));
      }
      return { mocks: [] };
    }

    const files = fs.readdirSync(this.mocksDir)
      .filter(f => f.endsWith('.js'))
      .map(f => {
        const stat = fs.statSync(path.join(this.mocksDir, f));
        return {
          file: f,
          target: f.replace('.js', ''),
          size: stat.size,
          modified: stat.mtime,
        };
      });

    if (options.json) {
      console.log(JSON.stringify({ mocks: files, count: files.length }, null, 2));
    } else {
      console.log(chalk.bold('\nMock Files\n'));
      if (files.length === 0) {
        console.log('  No mocks found.\n');
      } else {
        files.forEach((mock, i) => {
          console.log(`  ${chalk.cyan((i + 1).toString() + '.')} ${chalk.bold(mock.target)}`);
          console.log(`      ${chalk.dim(mock.file)} · ${chalk.dim(mock.modified.toLocaleDateString())}\n`);
        });
      }
    }

    return { mocks: files, count: files.length };
  }

  scan(options = {}) {
    const srcPaths = ['src', 'lib', 'app']
      .map(p => path.join(this.cwd, p))
      .filter(p => fs.existsSync(p));

    const dependencies = new Set();
    const _imports = new Set();

    for (const root of srcPaths) {
      const { walkFiles: _walkFiles } = require('../../utils/file-walker');
      const files = _walkFiles(root, { extensions: ['.js', '.jsx', '.ts', '.tsx'] });
      for (const file of files) {
        try {
          const content = fs.readFileSync(file, 'utf8');
          const importMatches = content.matchAll(/(?:import|require)\s+(?:.*\s+from\s+)?['"]([^'"]+)['"]/g);
          for (const match of importMatches) {
            const dep = match[1];
            if (dep.startsWith('.') || dep.startsWith('/')) continue;
            if (dep.endsWith('.css') || dep.endsWith('.scss') || dep.endsWith('.json')) continue;
            dependencies.add(dep);
          }
        } catch (err) {
          // Skip unreadable files
        }
      }
    }

    const deps = Array.from(dependencies).sort();

    if (options.json) {
      console.log(JSON.stringify({ dependencies: deps, count: deps.length }, null, 2));
    } else {
      console.log(chalk.bold('\nDiscovered Dependencies\n'));
      console.log(`  Found ${chalk.cyan(deps.length.toString())} external dependencies:\n`);
      deps.forEach(dep => {
        console.log(`  • ${chalk.cyan(dep)}`);
      });
      console.log(chalk.dim('\n  Generate mocks with: stdd mock generate <dependency>\n'));
    }

    return { dependencies: deps, count: deps.length };
  }
}

module.exports = { MockCommand };
